// Package lucide provides the set of Lucide Icons for NodX Go.
package lucide

import nodx "github.com/nodxdev/nodxgo"

// nodxgoSvgWrapper just creates the svg skeleton following the lucide
// guidelines. It is used by all the icons.
//
// https://lucide.dev/guide/
//
// It includes an extra attribute data-nodxgo="lucide" to globally
// identify the icons generated by this package. It can be used to
// style all the icons at once using CSS.
//
// Same as:
//
//	<svg
//		xmlns="http://www.w3.org/2000/svg"
//		width="24"
//		height="24"
//		viewBox="0 0 24 24"
//		fill="none"
//		stroke="currentColor"
//		stroke-width="2"
//		stroke-linecap="round"
//		stroke-linejoin="round"
//		data-nodxgo="lucide"
//	></svg>
func nodxgoSvgWrapper(children ...nodx.Node) nodx.Node {
	return nodx.El(
		"svg",
		nodx.Attr("xmlns", "http://www.w3.org/2000/svg"),
		nodx.Attr("width", "24"),
		nodx.Attr("height", "24"),
		nodx.Attr("viewBox", "0 0 24 24"),
		nodx.Attr("fill", "none"),
		nodx.Attr("stroke", "currentColor"),
		nodx.Attr("stroke-width", "2"),
		nodx.Attr("stroke-linecap", "round"),
		nodx.Attr("stroke-linejoin", "round"),
		nodx.Attr("data-nodxgo", "lucide"),
		nodx.Group(children...),
	)
}
