# https://taskfile.dev

version: "3"

tasks:
  codegen:
    desc: Run the code generator for the project and then format the code
    cmds:
      - go run ./cmd/codegen/.
      - task fmt

  fmt:
    desc: Run all the project formatters
    cmds:
      - deno fmt
      - go fmt ./...

  test:
    desc: Run all the project tests
    cmds:
      - deno test -A
      - go test ./...
